version: "3"
services:
  app:
    build: ./app
    container_name: "libwork"
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    container_name: "MySQL_Database-test-3"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro